##
## EPITECH PROJECT, 2022
## Makefile
## File description:
## hey. real programmers use vim
##

CC = gcc
CM = "sort_words"

all:
	$(CC) main.c -I. -o $(CM)

clean:
	echo "nothing to clean" 

fclean:
	rm $(CM)

re: fclean all
