##
## EPITECH PROJECT, 2022
## bscorewar [WSL: Ubuntu]
## File description:
## Makefile
##

all : ex1 ex2 ex3 ex4 ex5 ex6 ex7

ex1 :
	gcc -o ./part1/step1/write-some-text ./part1/step1/*.c -I.

ex2 :
	gcc -o ./part1/step2/write-a-number-as-text ./part1/step2/*.c -I.

ex3 :
	gcc -o ./part1/step3/write-a-number-as-int ./part1/step3/*.c -I.

ex4 :
	gcc -o ./part1/step4/without-padding ./part1/step4/*.c -I.

ex5 :
	gcc -o ./part1/step5/with-padding ./part1/step5/*.c -I.

ex6 :
	gcc -o ./part2/step1/yolotron-asm ./part2/step1/*.c -I.

ex7 :
	gcc -o ./part2/step2/yolotron-vm ./part2/step2/*.c -I.

fclean :
	rm -f ./part1/step1/write-some-text
	rm -f ./part1/step2/write-a-number-as-text
	rm -f ./part1/step3/write-a-number-as-in
	rm -f ./part1/step4/without-padding
	rm -f ./part1/step5/with-padding
	rm -f ./part2/step1/yolotron-asm
	rm -f ./part2/step2/yolotron-vm
	rm -f ./some-text.yolo ./number-as-text.yolo ./number-as-int.yolo ./several-variables.yolo ./one-structure.yolo