##
## EPITECH PROJECT, 2021
## Make Lib
## File description:
## Makefile
##

all:
	@make -C my/
	@make -C list/

clean:
	@make clean -C my/
	@make clean -C list/

fclean:
	@make fclean -C my/
	@make fclean -C list/
	@rm -rf *.a

re : fclean all
