##
## EPITECH PROJECT, 2023
## B-PDG-300-MPL-3-1-PDGD06-maxim.costa [WSL: Ubuntu]
## File description:
## Makefile
##

all:
	g++ -std=c++20 -Wall -Wextra -Werror MyCat.cpp -o MyCat

clean:
	rm -f *.o

fclean: clean
	rm -f MyCat

re: fclean all
