- name: Create /etc/poll
  ansible.builtin.file:
    path: /etc/poll
    state: directory
    mode: "0755"

- name: Extract and copy poll.tar to /etc/poll
  ansible.builtin.unarchive:
    src: poll.tar
    dest: /etc/poll
    owner: root
    group: root
    mode: "0755"

- name: Install python3-pip
  ansible.builtin.package:
    name: python3-pip
    state: present

- name: Install python3 requirements
  pip:
    requirements: /etc/poll/requirements.txt

- name: Template service
  ansible.builtin.template:
    src: poll.j2
    dest: /etc/systemd/system/poll.service
    mode: "0644"

- name: Enable service poll
  ansible.builtin.service:
    name: poll.service
    enabled: yes

- name: Restart service poll
  ansible.builtin.service:
    name: poll.service
    state: restarted