##
## EPITECH PROJECT, 2022
## Makefile
## File description:
## RUSH 3
##

all:
	make -C ./src/QT/QT5
	mv ./src/QT/QT5/QT5 ./MyGKrellm

clean:
	make clean -C ./src/QT/QT5

fclean: clean
	rm -rf MyGKrellm

re: fclean all