##
## EPITECH PROJECT, 2022
## B-CPE-200-MPL-2-1-dante-maxim.costa
## File description:
## Makefile
##

all:
	@make -C lib/my
	@make -C generator/
	@make -C solver/

clean:
	@ make -C lib/my clean
	@ make -C generator/ clean
	@ make -C solver/ clean

fclean:
	@ make -C lib/my fclean
	@ make -C generator fclean
	@ make -C solver fclean