##
## EPITECH PROJECT, 2023
## B-PDG-300-MPL-3-1-PDGD02-maxim.costa [WSL: Ubuntu]
## File description:
## Makefile
##

all: doop

doop: DoOp.hs
	ghc --make DoOp.hs -o doop

clean:
	rm -f doop DoOp.hi DoOp.o

fclean: clean
	rm -f doop

re: fclean all
