#!/usr/bin/env python3
##
## EPITECH PROJECT, 2021
## 101pong
## File description:
## MakeFile
##

NAME	=	106bombyx

all:	$(NAME)

$(NAME):
	cp $(NAME).py $@
	chmod a+x $@

clean:
	rm -rf $(NAME)

fclean:
	rm -rf $(NAME)

re: fclean all