#!/usr/bin/env python3
E=0.0
C=range
B=print
from argparse import ArgumentParser as G
from sys import argv as F,exit
from math import pi,sin
def A(t,v):
	E=1.0
	if v==0:return E
	A=E
	for D in C(t+1):B=v/(2*D+1);A*=sin(B)/B
	return A
def H(n):
	D=E;F=E
	for B in C(1,10000):D+=A(n,B/2)
	for B in C(10000):F+=A(n,B/2+0.5/2)
	G=A(n,5000)+A(n,0)+2*D+4*F;G*=5/60;return G
def I(n):
	B=E
	for D in C(10000):B+=A(n,D/2)
	B/=2;return B
def J(n):
	B=E
	for D in C(1,10000):B+=A(n,D/2)
	B*=2;B+=A(n,5000)+A(n,0);B/=4;return B
def help():B("USAGE\n    ./109borwein n\nDESCRIPTION\n    n   constant defining the integral to be computed");exit(0)
def K():A=G();A.add_argument('n',type=int);B=A.parse_args();return B
def D(nb):B(f"I0 = {nb:.10f}");B(f"diff = {pi/2-nb:.10f}")
def L():
	if len(F)>1 and F[1]=='-h':help()
	A=K();B('Midpoint:');D(I(A.n));B('\nTrapezoidal:');D(J(A.n));B('\nSimpson:');D(H(A.n));return 0
if __name__=='__main__':L()
